import type { Metadata } from "next";
import { Noto_Serif_JP } from "next/font/google";
import "@/app/globals.css";
import { VideoPlaybackProviderWrapper } from "@/components/VideoPlaybackProvider";
import { cn } from "@/components/utils/cn";

export const metadata: Metadata = {
  title: "IN BRAND",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
  },
};

const notoSerifJP = Noto_Serif_JP({
  preload: false,
  display: "swap",
  variable: "--font-noto-serif-jp",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={cn(notoSerifJP.variable)}>
      <body className="font-serifjp antialiased w-full">
        <VideoPlaybackProviderWrapper>{children}</VideoPlaybackProviderWrapper>
      </body>
    </html>
  );
}
